_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
#Code here
import numpy as np

# Create an array
my_array = np.array([10, 5, 7, 20, 15, -9, 33])
print(f"The array is: {my_array}")

# Find maximum and minimum values
max_value = np.max(my_array)
min_value = np.min(my_array)

print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")

The array is: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [2]:
#Code here
import numpy as np

# Accept an array of elements
# For this example, we'll use a predefined array
my_array = np.array([10, 5, 7, 20, 15, -9, 33])
print(f"The array is: {my_array}")

# Find the maximum value without using the max() function
if my_array.size == 0:
    max_val = None
else:
    max_val = my_array[0]
    for element in my_array:
        if element > max_val:
            max_val = element

print(f"The maximum value is: {max_val}")

The array is: [10  5  7 20 15 -9 33]
The maximum value is: 33


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [3]:
#Code here
import numpy as np

# Accept two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 4], [6, 8]])

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# Sum of the two matrices
sum_matrix = matrix1 + matrix2
print("\nSum of the matrices:")
print(sum_matrix)

# Subtraction of the two matrices
subtraction_matrix = matrix1 - matrix2
print("\nSubtraction of the matrices:")
print(subtraction_matrix)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[2 4]
 [6 8]]

Sum of the matrices:
[[ 3  6]
 [ 9 12]]

Subtraction of the matrices:
[[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [4]:
#Code here
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.rand(5, 6)
print("Original 5x6 Random Matrix:")
print(random_matrix)

# Add another row of random elements
new_row = np.random.rand(1, 6)
matrix_with_new_row = np.vstack((random_matrix, new_row))
print("\nMatrix with a new row added:")
print(matrix_with_new_row)

# Find the sum of each row
row_sums = np.sum(matrix_with_new_row, axis=1)
print("\nSum of each row:")
print(row_sums)

Original 5x6 Random Matrix:
[[0.11287158 0.13063346 0.03875053 0.07981425 0.2813785  0.97579217]
 [0.50147194 0.17935729 0.02820572 0.68276827 0.76558284 0.47590234]
 [0.20501672 0.43693453 0.59132186 0.24132745 0.06973967 0.68135546]
 [0.72370213 0.71239535 0.41493379 0.95723164 0.35587858 0.33995219]
 [0.24676511 0.93954831 0.25686566 0.10855873 0.41169367 0.73468343]]

Matrix with a new row added:
[[0.11287158 0.13063346 0.03875053 0.07981425 0.2813785  0.97579217]
 [0.50147194 0.17935729 0.02820572 0.68276827 0.76558284 0.47590234]
 [0.20501672 0.43693453 0.59132186 0.24132745 0.06973967 0.68135546]
 [0.72370213 0.71239535 0.41493379 0.95723164 0.35587858 0.33995219]
 [0.24676511 0.93954831 0.25686566 0.10855873 0.41169367 0.73468343]
 [0.58137231 0.97857092 0.30304604 0.71459887 0.46087155 0.09464728]]

Sum of each row:
[1.61924049 2.63328841 2.22569569 3.50409368 2.69811491 3.13310697]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [5]:
#Code here
import numpy as np

# Generate a random integer matrix of size 5x6
random_int_matrix = np.random.randint(0, 10, size=(5, 6))
print("Original 5x6 Random Integer Matrix:")
print(random_int_matrix)

# Add another column of random integers
new_column = np.random.randint(0, 10, size=(5, 1))
matrix_with_new_column = np.hstack((random_int_matrix, new_column))
print("\nMatrix with a new column added:")
print(matrix_with_new_column)

# Compute the sine of each element
sine_matrix = np.sin(matrix_with_new_column)
print("\nSine of each element in the new matrix:")
print(sine_matrix)

Original 5x6 Random Integer Matrix:
[[3 9 6 7 7 6]
 [5 9 8 5 9 7]
 [8 6 8 3 8 9]
 [7 1 7 1 5 8]
 [6 4 9 7 2 6]]

Matrix with a new column added:
[[3 9 6 7 7 6 8]
 [5 9 8 5 9 7 9]
 [8 6 8 3 8 9 1]
 [7 1 7 1 5 8 8]
 [6 4 9 7 2 6 8]]

Sine of each element in the new matrix:
[[ 0.14112001  0.41211849 -0.2794155   0.6569866   0.6569866  -0.2794155
   0.98935825]
 [-0.95892427  0.41211849  0.98935825 -0.95892427  0.41211849  0.6569866
   0.41211849]
 [ 0.98935825 -0.2794155   0.98935825  0.14112001  0.98935825  0.41211849
   0.84147098]
 [ 0.6569866   0.84147098  0.6569866   0.84147098 -0.95892427  0.98935825
   0.98935825]
 [-0.2794155  -0.7568025   0.41211849  0.6569866   0.90929743 -0.2794155
   0.98935825]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [6]:
#Code here
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.rand(5, 6)
print("Original 5x6 Random Matrix:")
print(random_matrix)

# Slice the matrix: 3rd and 4th rows (index 2 and 3) and 2nd, 3rd, and 4th columns (index 1, 2, and 3)
sliced_matrix = random_matrix[2:4, 1:4]
print("\nSliced Matrix (rows 3-4, columns 2-4):")
print(sliced_matrix)

Original 5x6 Random Matrix:
[[0.92850419 0.67032145 0.40464706 0.79323039 0.58383012 0.8656249 ]
 [0.0041371  0.43147993 0.29980791 0.28158629 0.22482634 0.73681496]
 [0.27217337 0.19585395 0.8322697  0.69624183 0.43492373 0.26370016]
 [0.48427064 0.62921671 0.61279072 0.34863598 0.81957277 0.3847542 ]
 [0.19148263 0.4101465  0.75414266 0.32349741 0.7908101  0.94944306]]

Sliced Matrix (rows 3-4, columns 2-4):
[[0.19585395 0.8322697  0.69624183]
 [0.62921671 0.61279072 0.34863598]]


### Great Job!